# 4장: 파이썬을 이용한 데이터 분석

## 7절: NumPy를 사용한 벡터와 행렬연산

### 01. 배열 사용하기

### 연습 문제 1

다음과 같은 행렬을 만든다

10 20 30 40

50 60 70 80

In [3]:
import numpy as np
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [7]:
b

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 연습 문제 2

다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],

              [ 5,  6,  7,  8,  9],
              
              [10, 11, 12, 13, 14]])
              
1. 이 행렬에서 값 7 을 인덱싱한다.

2. 이 행렬에서 값 14 을 인덱싱한다.

3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [9]:
m = np.array([[ 0, 1, 2, 3, 4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14]])

In [12]:
# 1. 
m[1,2]

7

In [25]:
# 2
m[-1, -1]
m[2, 4]

14

In [27]:
# 3
m[1,1:3]

array([6, 7])

In [42]:
# 4
m[1:,2:3]

array([[ 7],
       [12]])

In [38]:
# 5
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

### 연습 문제 3

다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [13]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
# 1
X[X % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [22]:
# 2
X[(X % 4 == 1)]

array([ 1,  5,  9, 13, 17])

In [25]:
# 3
X[(X % 3 == 0) & (X % 4 == 1)]

array([9])

### 02. NumPy 배열의 생성과 변형

### 연습 문제 1

In [60]:
import numpy as np
a = np.zeros(3)

b = np.ones(2)

c = np.linspace(10, 150, 15)

d = c.reshape(3,5)

a_b = np.hstack((a,b))

a_b_3 = np.vstack((a_b, a_b, a_b))

a_b_3_d = np.vstack((a_b_3, d))

a_b_3_d_2 = np.vstack((a_b_3_d, a_b_3_d))

a_b_3_d_2

array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

### 03. NumPy 배열의 연산

### 04. NumPy의 통계 함수

### 05. 난수 발생과 카운팅

In [4]:
import numpy as np


In [7]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};

SyntaxError: invalid syntax (<ipython-input-7-0f40127117db>, line 1)

In [11]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
[str(c) for c in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

---

In [1]:
pip install jupyterthemes


The following command must be run outside of the IPython shell:

    $ pip install jupyterthemes

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more informations on how to install packages:

    https://docs.python.org/3/installing/


In [4]:
import numpy as np
np.random.normal(0, 1, (3, 5))

array([[ 0.77043937, -0.95934904,  0.6624248 ,  0.52519942,  0.7866194 ],
       [-0.51972374,  0.70328364, -1.60374144,  0.18410482,  1.02836772],
       [ 2.20622804,  0.00837328,  0.00648998, -1.61446945,  0.27698256]])

32768.0