# 9. Structured Data : NumPy's Structured Arrays
**우리의 데이터는 종종 동질적인 값 배열로 잘 표현 될 수 있지만 때로는 그렇지 않습니다. 이 섹션에서는 복합 형 이기종 데이터를 효율적으로 저장하는 NumPy의 구조화 된 배열 및 레코드 배열을 사용하는 방법을 보여줍니다. 여기에 표시된 패턴은 간단한 조작에 유용하지만, 이와 같은 시나리오는 팬더 데이터 프레임의 사용에 도움이됩니다. 3 장에서 살펴 보겠습니다.**

In [2]:
import numpy as np

**Imagine that we have several categories of data on a number of people (say, name, age, and weight), and we'd like to store these values for use in a Python program. It would be possible to store these in three separate arrays:**

In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]


**그러나 이것은 조금 어색합니다. 여기에는 3 개의 배열이 관련되어 있다고 알려주는 것은 없습니다. 이 모든 데이터를 저장하기 위해 단일 구조를 사용할 수 있다면 더 자연 스럽습니다. NumPy는 복합 데이터 유형을 가진 배열 인 구조화 된 배열을 통해이를 처리 할 수 있습니다.**


In [5]:
x = np.zeros(4, dtype=int)


**우리는 유사하게 복합 데이터 타입 명세를 사용하여 구조화 된 배열을 만들 수 있습니다 :**

In [10]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [11]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25,  55. ) ('Bob', 45,  85.5) ('Cathy', 37,  68. )
 ('Doug', 19,  61.5)]


In [18]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'],
      dtype='<U10')

In [19]:
data[0]

('Alice', 25,  55.)

In [17]:
# Get the name from the last row
data[-1]['name']

'Doug'

In [20]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'],
      dtype='<U10')

# 1. Creating Structured Arrays

In [21]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [22]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [24]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [25]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

# 2. More Advanced Compound Types

In [26]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[ 0.,  0.,  0.], [ 0.,  0.,  0.], [ 0.,  0.,  0.]])
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


# 3. RecordArrays: Structured Arrays with a Twist

In [27]:
data['age']

array([25, 45, 37, 19])

In [28]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

# 4. On to Pandas